#pragma once
#include "gateway-ecu-adaptor.h"   // generated by sdbus-c++-xml2cpp
#include "EcuSomeIpClient.h"
#include <sdbus-c++/sdbus-c++.h>
#include <memory>

class GatewayDbusService
    : public sdbus::AdaptorInterfaces<com::vehicle::gateway::IDiagnosticManager_adaptor>
{
public:
    GatewayDbusService(sdbus::IConnection& connection,
                       std::shared_ptr<EcuSomeIpClient> someipClient);
    ~GatewayDbusService();

protected:
    // Generated interface overrides
    std::string GetCapabilities(const std::string& ecuId)    override;
    std::string ReadData       (const std::string& ecuId)    override;
    std::string ReadDataItem   (const std::string& ecuIdAndDataId) override;
    std::string GetFaults      (const std::string& ecuId)    override;
    std::string ClearFaults    (const std::string& ecuId)    override;
    std::string GetOperations  (const std::string& ecuId)    override;
    std::string ExecuteOperation(const std::string& ecuIdAndOpId) override;

private:
    std::shared_ptr<EcuSomeIpClient> someip_;
};
